### ISSUE TITLE
error in cvrt_annos_to_npy.py

### ISSUE THREAD

**Issue by scwuchung** [uci-cbcl/NoduleNet#40]
> Traceback (most recent call last):
  File "/home/chung/Downloads/NoduleNet-master/utils/LIDC/cvrt_annos_to_npy.py", line 163, in <module>
    annotation2masks(annos_dir, ctr_arr_save_dir)
  File "/home/chung/Downloads/NoduleNet-master/utils/LIDC/cvrt_annos_to_npy.py", line 46, in annotation2masks
    seriesuid, masks = xml2mask(f)
  File "/home/chung/Downloads/NoduleNet-master/utils/LIDC/cvrt_annos_to_npy.py", line 26, in xml2mask
    header, annos = parse(xml_file)
  File "/home/chung/Downloads/NoduleNet-master/utils/LIDC/pylung/annotation.py", line 67, in parse
    header = parse_header(root)
  File "/home/chung/Downloads/NoduleNet-master/utils/LIDC/pylung/annotation.py", line 99, in parse_header
    resp_hdr = root.findall('nih:ResponseHeader', NS)[0]

IndexError: list index out of range

**Comment by scwuchung** [comment]
the problem has been sovled

**Comment by RonDen** [comment]
> 

Hi, I have encountered the same problem, would you like to share how do you solve this?

**Comment by scwuchung** [comment]
> > 
> 
> Hi, I have encountered the same problem, would you like to share how do you solve this?
不好意思，兄弟，我记不太清了，实在不行你试试用我的代码吧，我当时改了之后是能运行的。链接：https://pan.baidu.com/s/1vB2fZ59GE4RCNmLu-VHZNQ?pwd=vdvu 
提取码：vdvu

**Comment by Khushi-Shah-1** [comment]
Any solution?

**Comment by SiyuanZhangGit** [comment]
> Hi, I have encountered the same problem, would you like to share how do you solve this?
> 不好意思，兄弟，我记不太清了，实在不行你试试用我的代码吧，我当时改了之后是能运行的。链接：https://pan.baidu.com/s/1vB2fZ59GE4RCNmLu-VHZNQ?pwd=vdvu
> 提取码：vdvu

可以给我发一份吗兄弟，729335790@qq.com

**Comment by chanuan** [comment]
> > > 
> > 
> > 
> > 嗨，我遇到了同样的问题，你想分享一下你是如何解决的吗？
> > 不好意思，兄弟，我记不太清了，实在不行你试试用我的代码吧，我当时改了之后是能运行的。链接：https://pan.baidu.com/s/1vB2fZ59GE4RCNmLu-VHZNQ?pwd=vdvu
> > 提取码：vdvu

Excuse me. The sharing has expired. Can you send me a copy? Thank you. nyg528943025@163.com
